name: cx
on:
  pull_request:
    branches:
      - master
#  push:
jobs:
  ast_scan:
    runs-on: ubuntu-latest
    name: Checkmarx scan run
    steps:
      - uses: actions/checkout@v2
      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz
      - name: Run AST scan
        uses: Checkmarx/ast-github-action@v0.28
        id: scan
        with:
          github_repo_token: ${{ secrets.GITHUB_TOKEN }}
          ast_uri: ${{ secrets.AST_URI }}
          ast_access_key_id: ${{ secrets.AST_ACCESS_KEY_ID }}
          ast_access_key_secret: ${{ secrets.AST_ACCESS_KEY_SECRET }}
          sca_user: ${{ secrets.SCA_USER }}
          sca_password: ${{ secrets.SCA_PASSWORD }}
          additional_params: --sca-resolver ./ScaResolver
          action_scan_complete_timeout_secs: 600
          high_results_threshold: 0
          medium_results_threshold: 10
